# Generated by Django 4.2.21 on 2025-08-14 13:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
                ('isbn_13', models.CharField(default='0000000000000', help_text='ISBN-13 format (13 digits)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN-13 must be exactly 13 digits', regex='^[0-9]{13}$')])),
                ('isbn_10', models.CharField(blank=True, help_text='ISBN-10 format (10 digits)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ISBN-10 must be exactly 10 digits', regex='^[0-9]{10}$')])),
                ('completed', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Library Entry',
                'verbose_name_plural': 'Library Entries',
            },
        ),
    ]
