# Generated by Django 4.2.21 on 2025-05-28 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryentry',
            options={'verbose_name': 'Library Entry', 'verbose_name_plural': 'Library Entries'},
        ),
        migrations.RemoveField(
            model_name='libraryentry',
            name='isbn',
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='isbn_10',
            field=models.CharField(blank=True, help_text='ISBN-10 format (10 digits)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ISBN-10 must be exactly 10 digits', regex='^[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='isbn_13',
            field=models.CharField(default='0000000000000', help_text='ISBN-13 format (13 digits)', max_length=13, validators=[django.core.validators.RegexValidator(message='ISBN-13 must be exactly 13 digits', regex='^[0-9]{13}$')]),
        ),
    ]
