# Generated by Django 4.2.21 on 2025-05-28 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_libraryentry_options_remove_libraryentry_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
