# Generated by Django 4.2.21 on 2025-05-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_add_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='sub_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
