# Generated by Django 4.2.21 on 2025-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_libraryentry_cover_image_url_libraryentry_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
