# Generated by Django 4.2.21 on 2025-05-29 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_libraryentry_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='isbn_13',
            field=models.CharField(default='0000000000000', help_text='ISBN-13 format (13 digits)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN-13 must be exactly 13 digits', regex='^[0-9]{13}$')]),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
